version: '3.7'

services:
    mssql:
        image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
        container_name: chatroom-mssql
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: Passw0rd
            MSSQL_PID: Express
        ports:
            - "1433:1433"
    rabbitmq:
        image: rabbitmq:3.7-management
        container_name: chatroom-rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - "5672:5672"
            - "15672:15672"
    stockbot:
        build: 
            context: ./JobsityChatroom
            dockerfile: ./JobsityChatroom.StockBot/Dockerfile
        depends_on:
            - rabbitmq
        environment:
            - DOTNET_ENVIRONMENT=Production
    api:
        build: 
            context: ./JobsityChatroom
            dockerfile: ./JobsityChatroom.WebAPI/Dockerfile
        depends_on:
            - rabbitmq
            - mssql
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production